name: Автосборка Music M (Unpacked)

on:
  workflow_dispatch:
    inputs:
      namevers:
        description: "Название релиза"
        required: true
        default: "🤖 Автосборка"
      descr:
        description: "Описание релиза"
        required: true
        default: "❌ Описание сборки отсутствует"
      release:
        description: "Выкинуть в релиз?"
        required: true
        default: false
        type: boolean
      prerelease:
        description: "Пререлиз?"
        required: true
        default: true
        type: boolean

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Unpacked]
        platform: [x64, x86, ARM64]

    runs-on: windows-latest
    env:
      Solution_Name: "VK UI3 (Package)"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Обновить TOKEN_STAT_DEFAULT_GATE
        run: |
          $repoName = "${{ github.repository }}".Split('/')[1]
          $content = Get-Content -Path "${{ github.workspace }}\VK UI3\StaticParams.cs"
          $updatedContent = $content -replace 'Environment.GetEnvironmentVariable\("TOKEN_STAT_DEFAULT_GATE"\)', '"${{ secrets.TOKEN_STAT_DEFAULT_GATE }}"'
          Set-Content -Path "${{ github.workspace }}\VK UI3\StaticParams.cs" -Value $updatedContent

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: dotnet restore "VK UI3/VK UI3.csproj"

      - name: Build solution
        run: |
          $platform = "${{ matrix.platform }}".ToLower()
          $runtimeId = if ($platform -eq "x64") { "win-x64" } elseif ($platform -eq "x86") { "win-x86" } else { "win-arm64" }
          
          dotnet build "VK UI3/VK UI3.csproj" `
            -c ${{ matrix.configuration }} `
            -p:Platform=${{ matrix.platform }} `
            -p:RuntimeIdentifier=$runtimeId `
            -p:TOKEN_STAT_DEFAULT_GATE="${{ secrets.TOKEN_STAT_DEFAULT_GATE }}"

      - name: Publish application
        run: |
          $platform = "${{ matrix.platform }}".ToLower()
          $runtimeId = if ($platform -eq "x64") { "win-x64" } elseif ($platform -eq "x86") { "win-x86" } else { "win-arm64" }
          
          dotnet publish "VK UI3/VK UI3.csproj" `
            -c ${{ matrix.configuration }} `
            -r $runtimeId `
            --self-contained true `
            -o "publish/${{ matrix.platform }}" `
            /p:Platform=${{ matrix.platform }} `
            /p:TOKEN_STAT_DEFAULT_GATE="${{ secrets.TOKEN_STAT_DEFAULT_GATE }}"

      - name: Create zip archive
        run: |
          $platform = "${{ matrix.platform }}"
          $zipName = "VK_UI3_${platform}_${{ matrix.configuration }}.zip"
          Compress-Archive -Path "publish/$platform/*" -DestinationPath $zipName

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VK_UI3_${{ matrix.platform }}_${{ matrix.configuration }}
          path: |
            VK_UI3_${{ matrix.platform }}_${{ matrix.configuration }}.zip

      - name: Извлечь версию
        id: get_version
        run: |
          $csprojPath = "${{ github.workspace }}\VK UI3\VK UI3.csproj"
          $doc = New-Object xml
          $doc.Load((Convert-Path $csprojPath))
          $version = $doc.SelectSingleNode('//AppxPackageVersion').InnerText
          echo "::set-output name=VERSION::$version"
          echo "Версия: $version"
        if: github.event.inputs.release == 'true'

      - name: Проверить существование релиза
        id: check_release
        run: |
          $version = "${{ steps.get_version.outputs.VERSION }}"
          $headers = @{
            "Authorization" = "token ${{ secrets.TOKEN }}"
          }
          $releases = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases" -Headers $headers
          $release = $releases | Where-Object { $_.tag_name -eq $version -and $_.draft -eq $false -and $_.prerelease -eq $false }
          if ($release) {
            Write-Host "Релиз с тегом $version уже существует"
            echo "::set-output name=exists::true"
          } else {
            Write-Host "Релиз с тегом $version не найден"
            echo "::set-output name=exists::false"
          }
        shell: pwsh
        if: github.event.inputs.release == 'true'

      - name: Создать релиз
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ github.event.inputs.namevers }}
          body: ${{ github.event.inputs.descr }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.release == 'true'

      - name: Загрузить файлы в релиз
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: VK_UI3_*.zip
          asset_name: VK_UI3_Unpacked_${{ matrix.platform }}
          tag: ${{ steps.get_version.outputs.VERSION }}
          overwrite: true
          file_glob: true
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.release == 'true'

      - name: Отправить сообщение в Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}
        run: |
          $telegramBotToken = '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          $telegramChatId = '${{ secrets.TELEGRAM_CHAT_ID }}'
          $releaseUrl = 'https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}'
          $message = @"
          <b>🎉 Новый релиз:</b> ${{ github.event.inputs.namevers }}
          <b>📦 Версия:</b> ${{ steps.get_version.outputs.VERSION }}
          <b>📝 Описание:</b> ${{ github.event.inputs.descr }}
          <b>🔗 <a href='$releaseUrl'>Ссылка на релиз</a></b>
          "@
          $uri = 'https://api.telegram.org/bot' + $telegramBotToken + '/sendMessage'
          $body = @{
              chat_id = $telegramChatId
              text = $message
              parse_mode = 'HTML'
          }
          $bodyJson = $body | ConvertTo-Json -Compress
          Invoke-RestMethod -Uri $uri -Method Post -Body $bodyJson -ContentType 'application/json'
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.release == 'true'
