name: Автосборка Music M (Unpacked - все платформы)

on:
  workflow_dispatch:
    inputs:
      namevers:
        description: "Название релиза"
        required: true
        default: "🤖 Автосборка"
      descr:
        description: "Описание релиза"
        required: true
        default: "❌ Описание сборки отсутствует"
      release:
        description: "Выкинуть в релиз?"
        required: true
        default: false
        type: boolean
      prerelease:
        description: "Пререлиз?"
        required: true
        default: true
        type: boolean

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        # Указание архитектур для сборки
        rid: [win-x64, win-x86, win-arm64]

    runs-on: windows-latest

    env:
      # Имя проекта для сборки
      Project_Name: "VK UI3"
      # Имя решения
      Solution_Name: "VK UI3.sln"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          node-version: 16
          fetch-depth: 0

      # Декодируем закодированный в base64 pfx и сохраняем Signing_Certificate
      - name: Decode the pfx
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
          $certificatePath = "${{ github.workspace }}\GitHubActionsWorkflow.pfx"
          [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

      # Обновить TOKEN_STAT_DEFAULT_GATE
      - name: Обновить TOKEN_STAT_DEFAULT_GATE
        run: |
          $repoName = "${{ github.repository }}".Split('/')[1]
          $content = Get-Content -Path "D:\a\$repoName\$repoName\VK UI3\StaticParams.cs"
          $updatedContent = $content -replace 'Environment.GetEnvironmentVariable\("TOKEN_STAT_DEFAULT_GATE"\)', '"${{ secrets.TOKEN_STAT_DEFAULT_GATE }}"'
          Set-Content -Path "D:\a\$repoName\$repoName\VK UI3\StaticParams.cs" -Value $updatedContent
          Write-Output $updatedContent

      # Установить .NET Core
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      # Добавить MSBuild в PATH
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # Восстановить зависимости
      - name: Restore dependencies
        run: dotnet restore ${{ env.Project_Name }}\${{ env.Project_Name }}.csproj

      # Устанавливаем сертификат, чтобы signtool мог его найти
      - name: Install PFX certificate
        run: |
          $certificatePath = "${{ github.workspace }}\GitHubActionsWorkflow.pfx"
          $password = ConvertTo-SecureString -String "${{ secrets.PFX_PASSWORD }}" -Force -AsPlainText
          Import-PfxCertificate -FilePath $certificatePath -CertStoreLocation Cert:\LocalMachine\My -Password $password

      # Сборка, публикация и подпись исполняемого файла
      - name: Build, Sign, and Zip the executable
        env:
          SIGN_PASSWORD: ${{ secrets.PFX_PASSWORD }}
        run: |
          $projectFile = "${{ env.Project_Name }}\${{ env.Project_Name }}.csproj"
          $outputDir = "build_output"
          
          # Публикуем приложение как автономный исполняемый файл
          dotnet publish `
            $projectFile `
            -c Unpacked `
            -r ${{ matrix.rid }} `
            --self-contained true `
            -o "$outputDir" `
            /p:PublishSingleFile=true
            
          $exePath = Get-ChildItem -Path "$outputDir" -Filter "*.exe" | Select-Object -First 1 | ForEach-Object { $_.FullName }
          
          if (-not $exePath) {
            throw "Исполняемый файл не найден в $outputDir"
          }
          
          # Подписываем исполняемый файл
          $signToolPath = (Get-Item "C:\Program Files (x86)\Windows Kits\10\bin\*\x64\signtool.exe").FullName | Select-Object -First 1
          
          if ($signToolPath) {
            Write-Host "Найден Signtool: $signToolPath"
            & "$signToolPath" sign /f "${{ github.workspace }}\GitHubActionsWorkflow.pfx" /p "${{ secrets.PFX_PASSWORD }}" /t http://timestamp.digicert.com /v $exePath
          } else {
            Write-Host "Signtool не найден. Подпись пропущена."
          }
          
          # Упаковываем в ZIP-архив
          $zipName = "${{ env.Project_Name }}_${{ matrix.rid }}.zip"
          Compress-Archive -Path "$outputDir\*" -DestinationPath "$zipName" -Force
          
          # Сохраняем путь к ZIP-архиву как переменную среды, чтобы использовать в следующем шаге
          echo "::set-output name=zip_file_path::$zipName"
          echo "::set-output name=zip_file_name::$zipName"

      # Удалить pfx
      - name: Remove the pfx
        run: |
          $certificatePath = "${{ github.workspace }}\GitHubActionsWorkflow.pfx"
          Remove-Item -path "$certificatePath"
      
      # Загружаем ZIP-архивы как артефакты сборки
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: Executable ${{ matrix.rid }}
          path: "*.zip"

      # === Шаги для создания релиза и уведомлений ===
      
      - name: Извлечь версию
        id: get_version
        run: |
          $repoName = "${{ github.repository }}".Split('/')[1]
          $csprojPath = "D:\a\$repoName\$repoName\${{ env.Project_Name }}\${{ env.Project_Name }}.csproj"
          $doc = New-Object xml
          $doc.Load((Convert-Path $csprojPath))
          # Ищем тег <Version>
          $version = $doc.SelectSingleNode('//Version').InnerText
          echo "::set-output name=VERSION::$version"
          echo "Версия: $version"
        continue-on-error: true
        if: github.event.inputs.release == 'true'

      - name: Вывести версию
        run: |
          echo "Извлеченная версия: ${{ steps.get_version.outputs.VERSION }}"
      - name: Проверить существование релиза
        id: check_release
        run: |
          $version = "${{ steps.get_version.outputs.VERSION }}"
          $headers = @{
            "Authorization" = "token ${{ secrets.TOKEN }}"
          }
          $releases = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases" -Headers $headers
          $release = $releases | Where-Object { $_.tag_name -eq $version -and $_.draft -eq $false -and $_.prerelease -eq $false }
          if ($release) {
            Write-Host "Релиз с тегом $version уже существует"
            echo "::set-output name=exists::true"
          } else {
            Write-Host "Релиз с тегом $version не найден"
            echo "::set-output name=exists::false"
          }
        shell: pwsh
        if: github.event.inputs.release == 'true'

      - name: Создать релиз
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ github.event.inputs.namevers }}
          body: ${{ github.event.inputs.descr }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.release == 'true'

      - name: Загрузить файлы в релиз
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: "*.zip"
          tag: ${{ steps.get_version.outputs.VERSION }}
          overwrite: true
          file_glob: true
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.release == 'true'

      - name: Отправить сообщение в Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}
        run: |
          $telegramBotToken = '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          $telegramChatId = '${{ secrets.TELEGRAM_CHAT_ID }}'
          $releaseUrl = 'https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}'
          $message = @"
          <b>🎉 Новый релиз:</b> ${{ github.event.inputs.namevers }}
          <b>📦 Версия:</b> ${{ steps.get_version.outputs.VERSION }}
          <b>📝 Описание:</b> ${{ github.event.inputs.descr }}
          <b>🔗 <a href='$releaseUrl'>Ссылка на релиз</a></b>
          "@
          $uri = 'https://api.telegram.org/bot' + $telegramBotToken + '/sendMessage'
          $body = @{
              chat_id = $telegramChatId
              text = $message
              parse_mode = 'HTML'
          }
          $bodyJson = $body | ConvertTo-Json -Compress
          Invoke-RestMethod -Uri $uri -Method Post -Body $bodyJson -ContentType 'application/json'
